# Site settings
title: Devnest Blog
email: me@miladrk.com
description: > # this means to ignore newlines until "baseurl:"
  We are a group of software developers, sharing our ideas and experience about software and tech. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.devnest.io" # the base hostname & protocol for your site
twitter_username: milianoo
github_username:  milianoo

# Build settings
markdown: kramdown
